/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/layout/aside/index.vue')['default']
    Avatar: typeof import('./src/components/layout/header/right/components/avatar.vue')['default']
    Bell: typeof import('./src/components/layout/header/right/components/bell.vue')['default']
    BreadCrumb: typeof import('./src/components/layout/header/left/breadCrumb/index.vue')['default']
    Clothes: typeof import('./src/components/layout/header/right/components/clothes.vue')['default']
    CollapseIcon: typeof import('./src/components/layout/header/right/components/collapseIcon.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./src/components/layout/footer/index.vue')['default']
    Hamburger: typeof import('./src/components/layout/header/left/hamburger/index.vue')['default']
    HasChildren: typeof import('./src/components/layout/aside/hasChildren.vue')['default']
    Header: typeof import('./src/components/layout/header/index.vue')['default']
    ICarbonUser: typeof import('~icons/carbon/user')['default']
    ICilLanguage: typeof import('~icons/cil/language')['default']
    IconBox: typeof import('./src/components/layout/header/right/iconBox.vue')['default']
    IIcBaselineZoomInMap: typeof import('~icons/ic/baseline-zoom-in-map')['default']
    IIcBaselineZoomOutMap: typeof import('~icons/ic/baseline-zoom-out-map')['default']
    IMaterialSymbols360: typeof import('~icons/material-symbols/360')['default']
    IMaterialSymbolsSearchSharp: typeof import('~icons/material-symbols/search-sharp')['default']
    IMaterialSymbolsZoomOutMapSharp: typeof import('~icons/material-symbols/zoom-out-map-sharp')['default']
    IMdiBellOutline: typeof import('~icons/mdi/bell-outline')['default']
    IMingcuteTShirtLine: typeof import('~icons/mingcute/t-shirt-line')['default']
    Language: typeof import('./src/components/layout/header/right/components/language.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Left: typeof import('./src/components/layout/header/left/index.vue')['default']
    Logo: typeof import('./src/components/layout/aside/logo.vue')['default']
    Main: typeof import('./src/components/layout/main/index.vue')['default']
    NoChildren: typeof import('./src/components/layout/aside/noChildren.vue')['default']
    Right: typeof import('./src/components/layout/header/right/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/layout/header/right/components/search.vue')['default']
    Switch: typeof import('./src/components/layout/header/right/components/switch.vue')['default']
    TagBox: typeof import('./src/components/layout/tagBox/index.vue')['default']
    Username: typeof import('./src/components/layout/header/right/components/username.vue')['default']
  }
}
